# Generated by Django 3.1.3 on 2021-01-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_service_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_order',
            name='stitle',
            field=models.CharField(max_length=500),
        ),
    ]
