# Generated by Django 3.1.3 on 2020-12-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proximaweb', '0002_cuscontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CusContact',
        ),
    ]
