# Generated by Django 3.1.3 on 2020-12-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
                ('c_name', models.CharField(max_length=200)),
                ('c_title', models.CharField(max_length=100)),
                ('c_des', models.TextField()),
            ],
        ),
    ]
