# Generated by Django 3.1.3 on 2021-01-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_paidcourse_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidSec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.IntegerField()),
                ('time', models.TextField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
