# Generated by Django 3.1.3 on 2021-01-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('efname', models.CharField(max_length=100)),
                ('elname', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=50)),
                ('econtact', models.CharField(max_length=12)),
                ('eparadd', models.CharField(max_length=200)),
                ('epreadd', models.CharField(max_length=200)),
                ('eoption', models.CharField(max_length=100)),
            ],
        ),
    ]
