# Generated by Django 3.1.3 on 2021-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitle', models.CharField(max_length=20)),
                ('sdes', models.TextField()),
                ('sreq', models.TextField()),
                ('sdel', models.DateTimeField()),
                ('sadd', models.TextField()),
            ],
        ),
    ]
