# Generated by Django 3.1.3 on 2020-12-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_email', models.EmailField(max_length=50)),
                ('cus_sub', models.CharField(max_length=200)),
                ('cus_sms', models.TextField()),
            ],
        ),
    ]
