# Generated by Django 3.1.3 on 2020-12-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CusContact',
            new_name='Cus_Contact',
        ),
    ]
